os: 
  - linux
  - osx
  - windows
language: c
compiler: gcc

env:
  - FILE_ROOT="prometheus-exporter"

script:
  if [ "$TRAVIS_OS_NAME" == "windows" ]; then
    7z a -tzip $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip README.md q LICENSE examples;
  else
    tar  -zcvf $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tgz README.md q LICENSE examples/;
  fi

deploy:
  provider: releases
  api_key: "$GITHUB_APIKEY"
  file: 
    if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip;
    else
      $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tgz;
    fi
  on:
    tags: true
  skip_cleanup: 'true'

