os: 
  - linux
  - osx
  - windows
language: c
compiler: gcc


before_install:
  - export FILE_ROOT="prometheus-exporter"
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      export FILE_TAIL="zip";
    else
      export FILE_TAIL="tgz";
    fi
  - export FILE_NAME=$FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.$FILE_TAIL

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      7z a -tzip $FILE_NAME README.md q LICENSE examples;
    else
      tar  -zcvf $FILE_NAME README.md q LICENSE examples/;
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_APIKEY"
  file: "$FILE_NAME"
  on:
    tags: true
  skip_cleanup: 'true'

