os: 
  - linux
  - osx
  - windows
language: c
compiler: gcc

before_install:
  - export FILE_ROOT="mqtt"
  - export TESTS="True"
  - export BUILD="True"

  # Run instructions to install the C/C++ requirements (BUILD_HOME) set in place of PAHO_HOME/HDF5_HOME etc.
  - if [[ $BUILD == "True" ]]; then
      chmod +x travis_setup.sh; 
      ./travis_setup.sh;
      export BUILD_HOME=$TRAVIS_BUILD_DIR/cbuild
      export LIB="cmake/$FILE_ROOT/lib";
      mkdir cmake;
    else
      export LIB="";
    fi

  # Define location to get kdb+ [MLW](64) address to curl from and dir
  - if [[ $TESTS == "True" && $TRAVIS_OS_NAME == "linux" ]]; then
      QLIBDIR=l64; OD=$L64;
    elif [[ $TESTS == "True" && $TRAVIS_OS_NAME == "osx" ]]; then 
      QLIBDIR=m64; OD=$M64;
    elif [[ $TESTS == "True" && $TRAVIS_OS_NAME == "windows" ]]; then 
      QLIBDIR=w64; OD=$W64;
    elif [[ $TESTS == "True" ]]; then
      echo "unknown OS ('$TRAVIS_OS_NAME')" >&2; exit 1;
    fi

  # Set up q for testing and execute tests on multiple 
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      export CMAKE_TYPE="TestRelease";
      export QLIBDIR;
      mkdir qhome;
      export QHOME=$(pwd)/qhome;
      export PATH=$QHOME/$QLIBDIR:$PATH;
      export LD_LIBRARY_PATH=$LIB:$LD_LIBRARY_PATH;
      curl -o qhome/q.zip -L $OD;
      unzip -d qhome qhome/q.zip;
      rm qhome/q.zip;
      echo -n $QLIC_KC |base64 --decode > qhome/kc.lic;
    else
      export CMAKE_TYPE="Release";
      echo No kdb+, no tests;
    fi
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      export FILE_TAIL="zip";
    else
      export FILE_TAIL="tgz";
    fi
  - export FILE_NAME=$FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.$FILE_TAIL

  # Make binaries for the library as appropriate
  - if [[ $BUILD == "True" && $TRAVIS_OS_NAME == "windows" ]]; then
      cd cmake && cmake -DCMAKE_BUILD_TYPE=${CMAKE_TYPE} -G "Visual Studio 15 2017 Win64" .. ;
      export MSBUILD_PATH="/c/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/";
      export PATH=$PATH:$MSBUILD_PATH;
      MSBuild.exe INSTALL.vcxproj //m //nologo //verbosity:normal //p:Configuration=Release //p:Platform=x64;
      cd ..;
    elif [[ $BUILD == "True" && ( $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ) ]]; then
      cd cmake && cmake .. -DCMAKE_BUILD_TYPE=${CMAKE_TYPE} && make install && cd .. ;
    fi

script:
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      q test.q tests/ -q;
    fi
  - if [[ $TRAVIS_OS_NAME == "windows" && $BUILD == "True" ]]; then
      7z a -tzip -r $FILE_NAME ./cmake/$FILE_ROOT/*;
    elif [[ $BUILD == "True" && ( $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ) ]]; then  
      tar  -zcvf $FILE_NAME -C cmake/$FILE_ROOT .;
    elif [[ $TRAVIS_OS_NAME == "windows" ]]; then
      7z a -tzip $FILE_NAME README.md install.bat LICENSE q examples;
    elif [[ $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx" ]]; then
      tar  -zcvf $FILE_NAME README.md install.sh LICENSE q examples;
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_APIKEY"
  file: "$FILE_NAME"
  on:
    tags: true
  skip_cleanup: 'true'

