os: linux
language: c
compiler: gcc


stage:
  - build Release

jobs:
  before include:
    - export FILE_ROOT = "prometheus-exporter"
  include:
    # LINUX BUILD
    - stage: build Release
      os: linux
      script:
        tar -zcvf $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tgz README.md LICENSE q examples/
      deploy:
        provider: releases
        api_key: "$GITHUB_APIKEY"
        file: $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tgz
        on:
          tags: true
        skip_cleanup: 'true'

    # OSX BUILD
    - stage: build Release
      os: osx
      script:
        tar -zcvf $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tgz README.md q LICENSE examples/
      deploy:
        provider: releases
        api_key: "$GITHUB_APIKEY"
        file: $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.tgz
        on:
          tags: true
        skip_cleanup: 'true'

    # WINDOWS BUILD
    - stage: build Release
      os: windows
      script:
        7z a -tzip $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip README.md q LICENSE examples
      deploy:
        provider: releases
        api_key: "$GITHUB_APIKEY"
        file: $FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip
        on:
          tags: true
        skip_cleanup: 'true'
