os: 
  - linux
  - osx
  - windows
language: c
compiler: gcc

before_install:
  - export FILE_ROOT="mqtt"
  - export TESTS="False"
  - export BUILD="True"

  # Run instructions to install the C/C++ requirements (BUILD_HOME) set in place of PAHO_HOME/HDF5_HOME etc.
  - if [[ $BUILD == "True" ]]; then
      chmod +x travis_setup.sh; 
      ./travis_setup.sh;
      export BUILD_HOME=$(pwd)/build
      export LIB="lib";
      mkdir cmake;
    else
      export LIB="";
    fi

  # Make binaries for the library as appropriate
  - if [[ $BUILD == "True" && $TRAVIS_OS_NAME == "windows"]]; then
      cd cmake && cmake -G "Visual Studio 15 2017 Win64" ..;
    elif [[ $BUILD == "True" && $TRAVIS_OS_NAME == "linux" || $TRAVIS_OS_NAME == "osx"]]; then
      cd cmake && cmake ..;
    fi

  # Define location to get kdb+ [MLW](64) address to curl from and dir
  - if [[ $TESTS == "True" && $TRAVIS_OS_NAME == "linux" ]]; then
      QLIBDIR=l64; OD=$L64;
    elif [[ $TESTS == "True" && $TRAVIS_OS_NAME == "osx" ]]; then 
      QLIBDIR=m64; OD=$M64;
    elif [[ $TESTS == "True" && $TRAVIS_OS_NAME == "windows" ]]; then 
      QLIBDIR=w64; OD=$W64;
    elif [[ $TESTS == "True" ]]; then
      echo "unknown OS ('$TRAVIS_OS_NAME')" >&2; exit 1;
    fi

  # Set up q for testing and execute tests on multiple 
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      export QLIBDIR;
      mkdir qhome;
      export QHOME=$(pwd)/qhome;
      export PATH=$QHOME/$QLIBDIR:$PATH;
      curl -o qhome/q.zip -L $OD;
      unzip -d qhome qhome/q.zip;
      rm qhome/q.zip;
      echo -n $QLIC_KC |base64 --decode > qhome/kc.lic;
      curl -fsSL -o test.q https://github.com/KxSystems/embedpy/raw/master/test.q;
    else
      echo No kdb+, no tests;
    fi
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      export FILE_TAIL="zip";
    else
      export FILE_TAIL="tgz";
    fi
  - export FILE_NAME=$FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.$FILE_TAIL

script:
  - if [[ $TESTS == "True" && "x$OD" != "x" && "x$QLIC_KC" != "x" ]]; then
      q test.q tests/ -q;
    fi
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      7z a -tzip $FILE_NAME README.md install.bat  LICENSE q examples $LIB;
    else
      tar  -zcvf $FILE_NAME README.md install.sh LICENSE q examples $LIB;
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_APIKEY"
  file: "$FILE_NAME"
  on:
    tags: true
  skip_cleanup: 'true'

