os: 
  - linux
  - osx
  - windows
language: c
compiler: gcc

env:
  global:
    - FILE_ROOT="prometheus-exporter"
    - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
        FILE_TAIL="zip";
      else
        FILE_TAIL="tgz";
    - FILE_NAME=$FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.$FILE_TAIL 

script:
  - echo $FILE_NAME
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      7z a -tzip $FILE_NAME README.md q LICENSE examples;
    else
      tar  -zcvf $FILE_NAME README.md q LICENSE examples/;
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_APIKEY"
  file: "$FILE_NAME"
  on:
    tags: true
  skip_cleanup: 'true'

