os: 
  - linux
  - osx
  - windows
language: c
compiler: gcc

before_install:
  - export FILE_ROOT="prometheus-exporter"
  - export TESTS="False"
  - export COVERITY="False"
  - export BUILD="False"
  - if [[ $BUILD == "True" ]]; then
      export LIB="lib";
    else
      export LIB="";
    fi
  - if [[ $TESTS == "True" ]]; then
      if [ $TRAVIS_OS_NAME = linux ]; then 
        QLIBDIR=l64;
        OD="linux";
      else if [ $TRAVIS_OS_NAME = osx ]; then 
        QLIBDIR=m64;
        OD="mac";
      else if [ $TRAVIS_OS_NAME = windows ];then 
        QLIBDIR=w64;
        OD="windows;
      fi
      export QLIBDIR;
      echo $QLIBDIR;
      mkdir q;
      export QHOME=$(pwd)/q;
      export PATH=$QHOME/$QHOME;
    fi
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then
      export FILE_TAIL="zip";
    else
      export FILE_TAIL="tgz";
    fi
  - export FILE_NAME=$FILE_ROOT-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.$FILE_TAIL

script:
  - if [ "$TRAVIS_OS_NAME" == "windows" ]; then
      7z a -tzip $FILE_NAME README.md q LICENSE examples $LIB;
    else
      tar  -zcvf $FILE_NAME README.md q LICENSE examples $LIB;
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_APIKEY"
  file: "$FILE_NAME"
  on:
    tags: true
  skip_cleanup: 'true'

